server:
    port: 8080
    error:
        include-message: always
        include-binding-errors: always
    servlet:
        session:
            timeout: 1h
spring:
    application:
        name: authenticationproject
    mail:
        host: smtp.gmail.com
        port: 587
        username: email@gmail.com
        password: password
        protocol: smtp
        properties:
            mail:
                smtp:
                auth: true
                starttls:
                    enable: true
    datasource:
        url: jdbc:mysql://localhost:3306/spring_table?useSSL=false&serverTimezone=UTC
        username: root
        password:
        driver-class-name: com.mysql.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update  #creating table automatically
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
        show-sql: true

    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        cache: false